imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

#additional parameters
parameters:
    hwi_oauth.user.provider.fosub_bridge.class: LMammino\Bundle\JHACBundle\Security\Core\User\FOSUBUserProvider

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        app_url: %app_url%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [OryzoneBoilerplateBundle, LMamminoJHACBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        #entity_managers:
        #    default:
        #        mappings:
        #            SonataNotificationBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

#FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: LMammino\Bundle\JHACBundle\Entity\User

#HWIOauthBundle
hwi_oauth:
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_client_id%
            client_secret:       %facebook_client_secret%
            scope:               "email, user_birthday, user_location, publish_stream"
            user_response_class: \HWI\Bundle\OAuthBundle\OAuth\Response\AdvancedPathUserResponse
            paths:
                identifier: id
                nickname: username
                first_name: firstname
                last_name: lastname
                email: email
        twitter:
            type:                twitter
            client_id:           %twitter_client_id%
            client_secret:       %twitter_client_secret%
        salesforce:
            type:                oauth2
            client_id:           %salesforce_client_id%
            client_secret:       %salesforce_client_secret%
            access_token_url:    https://login.salesforce.com/services/oauth2/token
            authorization_url:   https://login.salesforce.com/services/oauth2/authorize
            infos_url:           https://na15.salesforce.com/services/data/v26.0/sobjects/User/005i0000000YojvAAC
            scope:               ""
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\AdvancedPathUserResponse
            paths:
                identifier: Id
                nickname:   CommunityNickname
                first_name: FirstName
                last_name:  LastName
                realname:   Name
                email:      Email
    fosub:
        username_iterations: 30
        # mapping between resource owners (see below) and properties
        properties:
            #github: githubId
            #google: googleId
            facebook: facebookId
            salesforce: salesforceId
    firewall_name: main
    connect: ~